import numpy as np

bad_direction_kpi_dict = {"enb_init_gnb_mod_dur_wmean" : "max",
"gnb_add_overall_duration_wmean": "max",
"enb_init_gnb_mod_dur_wmean" : "max",
"gnb_add_overall_duration_wmean": "max",
"gnb_change_dur_wmean": "max",
"gnb_init_gnb_mod_dur_wmean" : "max",
'update_pdp_success_wmean' : "min",
'delete_pdp_success_wmean' : "min",
'ims_dereg_succ_ratio_wmean' : "min",
'ims_srvcc_succ_ratio_wmean' : "min",
'ims_reg_succ_ratio_wmean' : "min",
'ims_sess_change_succ_ratio_wmean' : "min",
'ims_rereg_succ_ratio_wmean' : "min",
'ims_sess_setup_succ_ratio_wmean' : "min",
'gnb_add_overall_succ_ratio_wmean' : "min",
'csfb_call_succ_wmean' : "min",
'srvcc_succ_ratio_wmean' : "min",
'attach_wmean'  : "min",
'lte_attach_wmean' : "min",
'ims_srvcc_delay_wmean' : "max",
'ims_sess_change_delay_wmean' : "max",
'ims_reg_delay_wmean' : "max",
'ims_dereg_delay_wmean' : "max",
'ims_call_setup_delay_wmean' : "max",
'ims_rereg_delay_wmean' : "max",
'rtp_delay_ul_wmean' : "max",
'rtp_delay_dl_wmean' : "max",
'harq_loss_dl_wmean' : "max",
'harq_loss_ul_wmean' : "max",
'rlc_loss_dl_wmean' : "max",
'rlc_loss_ul_wmean' : "max",
'pkt_loss_net_ul_wmean' : "max",
'pkt_loss_term_dl_wmean' : "max",
'pkt_loss_term_ul_wmean' : "max",
'pkt_loss_net_dl_wmean' : "max",
'rtp_packet_loss_dl_wmean' : "max",
'rtp_packet_loss_ul_wmean' : "max",
'pdcp_loss_dl_wmean' : "max",
'pdcp_loss_ul_wmean' : "max",
'pdcp_tp_dl_wmean' : "min",
'pdcp_tp_ul_wmean' : "min",
'tcp_tp_dl_wmean' : "min",
'tcp_tp_ul_wmean' : "min",
'rtt_net_wmean' : "max",
'rtt_term_wmean' : "max",
'udp_tp_class_ul_wmean' : "min",
'udp_tp_class_dl_wmean' : "min",
'tcp_tp_class_ul_wmean' : "min",
'delete_session_response_time_wmean': "max",
's1_ho_wmean' : "min",
'lte_attach_wmean' : "min",
'abnormal_lte_conn_rel_ratio_wmean' : "max",
'create_session_wmean' : "min",
's1_ho_exec_time_wmean' : "max",
'x2_ho_wmean' : "min",
'x2_ho_exec_time_wmean' : "max",
'detach_wmean' : "min",
'ims_abnorm_sess_rel_ratio_wmean' : "max",
'bytes_dl_sum' : "max",
'bytes_ul_sum' : "max",
'x2_ho_avg': 'min',
'rsrp_wmean': 'min',
'rsrq_wmean':'min',
'serving_rsrp_wmean': 'min',
'serving_rsrq_wmean':'min',
'x2_ho_attempts_wmean' : "max",
's1_ho_attempts_wmean' : "max",
'ims_call_setup_time_wmean' : "max",
'rtp_mos_dl_wmean' : "min",
'rtp_mos_ul_wmean' : "min",
'rtp_jitter_dl_wmean' : "max",
'rtp_jitter_ul_wmean' : "max",
"enb_init_gnb_mod_dur_sum" : "max",
"gnb_add_overall_duration_sum": "max",
"enb_init_gnb_mod_dur_sum" : "max",
"gnb_add_overall_duration_sum": "max",
"gnb_change_dur_sum": "max",
"gnb_init_gnb_mod_dur_sum" : "max",
'update_pdp_success_sum' : "min",
'delete_pdp_success_sum' : "min",
'ims_dereg_succ_ratio_sum' : "min",
'ims_srvcc_succ_ratio_sum' : "min",
'ims_reg_succ_ratio_sum' : "min",
'ims_sess_change_succ_ratio_sum' : "min",
'ims_rereg_succ_ratio_sum' : "min",
'ims_sess_setup_succ_ratio_sum' : "min",
'gnb_add_overall_succ_ratio_sum' : "min",
'csfb_call_succ_sum' : "min",
'srvcc_succ_ratio_sum' : "min",
'attach_sum'  : "min",
'lte_attach_sum' : "min",
'ims_srvcc_delay_sum' : "max",
'ims_sess_change_delay_sum' : "max",
'ims_reg_delay_sum' : "max",
'ims_dereg_delay_sum' : "max",
'ims_call_setup_delay_sum' : "max",
'ims_rereg_delay_sum' : "max",
'rtp_delay_ul_sum' : "max",
'rtp_delay_dl_sum' : "max",
'harq_loss_dl_sum' : "max",
'harq_loss_ul_sum' : "max",
'rlc_loss_dl_sum' : "max",
'rlc_loss_ul_sum' : "max",
'pkt_loss_net_ul_sum' : "max",
'pkt_loss_term_dl_sum' : "max",
'pkt_loss_term_ul_sum' : "max",
'pkt_loss_net_dl_sum' : "max",
'rtp_packet_loss_dl_sum' : "max",
'rtp_packet_loss_ul_sum' : "max",
'pdcp_loss_dl_sum' : "max",
'pdcp_loss_ul_sum' : "max",
'pdcp_tp_dl_sum' : "min",
'pdcp_tp_ul_sum' : "min",
'tcp_tp_dl_sum' : "min",
'tcp_tp_ul_sum' : "min",
'rtt_net_sum' : "max",
'rtt_term_sum' : "max",
'udp_tp_class_ul_sum' : "min",
'udp_tp_class_dl_sum' : "min",
'tcp_tp_class_ul_sum' : "min",
'delete_session_response_time_sum': "max",
's1_ho_sum' : "min",
'lte_attach_sum' : "min",
'abnormal_lte_conn_rel_ratio_sum' : "max",
'create_session_sum' : "min",
's1_ho_exec_time_sum' : "max",
'x2_ho_sum' : "min",
'x2_ho_exec_time_sum' : "max",
'detach_sum' : "min",
'ims_abnorm_sess_rel_ratio_sum' : "max",
'bytes_dl_sum' : "max",
'bytes_ul_sum' : "max",
'x2_ho_avg': 'min',
'rsrp_sum': 'min',
'rsrq_sum':'min',
'serving_rsrp_sum': 'min',
'serving_rsrq_sum':'min',
'x2_ho_attempts_sum' : "max",
's1_ho_attempts_sum' : "max",
'ims_call_setup_time_sum' : "max",
'rtp_mos_dl_sum' : "min",
'rtp_mos_ul_sum' : "min",
'rtp_jitter_dl_sum' : "max",
'rtp_jitter_ul_sum' : "max",
"enb_init_gnb_mod_dur_sample" : "max",
"gnb_add_overall_duration_sample": "max",
"enb_init_gnb_mod_dur_sample" : "max",
"gnb_add_overall_duration_sample": "max",
"gnb_change_dur_sample": "max",
"gnb_init_gnb_mod_dur_sample" : "max",
'update_pdp_success_sample' : "max",
'delete_pdp_success_sample' : "max",
'ims_dereg_succ_ratio_sample' : "max",
'ims_srvcc_succ_ratio_sample' : "max",
'ims_reg_succ_ratio_sample' : "max",
'ims_sess_change_succ_ratio_sample' : "max",
'ims_rereg_succ_ratio_sample' : "max",
'ims_sess_setup_succ_ratio_sample' : "max",
'gnb_add_overall_succ_ratio_sample' : "max",
'csfb_call_succ_sample' : "max",
'srvcc_succ_ratio_sample' : "max",
'attach_sample'  : "max",
'lte_attach_sample' : "max",
'ims_srvcc_delay_sample' : "max",
'ims_sess_change_delay_sample' : "max",
'ims_reg_delay_sample' : "max",
'ims_dereg_delay_sample' : "max",
'ims_call_setup_delay_sample' : "max",
'ims_rereg_delay_sample' : "max",
'rtp_delay_ul_sample' : "max",
'rtp_delay_dl_sample' : "max",
'harq_loss_dl_sample' : "max",
'harq_loss_ul_sample' : "max",
'rlc_loss_dl_sample' : "max",
'rlc_loss_ul_sample' : "max",
'pkt_loss_net_ul_sample' : "max",
'pkt_loss_term_dl_sample' : "max",
'pkt_loss_term_ul_sample' : "max",
'pkt_loss_net_dl_sample' : "max",
'rtp_packet_loss_dl_sample' : "max",
'rtp_packet_loss_ul_sample' : "max",
'pdcp_loss_dl_sample' : "max",
'pdcp_loss_ul_sample' : "max",
'pdcp_tp_dl_sample' : "max",
'pdcp_tp_ul_sample' : "max",
'tcp_tp_dl_sample' : "max",
'tcp_tp_ul_sample' : "max",
'rtt_net_sample' : "max",
'rtt_term_sample' : "max",
'udp_tp_class_ul_sample' : "max",
'udp_tp_class_dl_sample' : "max",
'tcp_tp_class_ul_sample' : "max",
'delete_session_response_time_sample': "max",
's1_ho_sample' : "max",
'lte_attach_sample' : "max",
'abnormal_lte_conn_rel_ratio_sample' : "max",
'create_session_sample' : "max",
's1_ho_exec_time_sample' : "max",
'x2_ho_sample' : "max",
'x2_ho_exec_time_sample' : "max",
'detach_sample' : "max",
'ims_abnorm_sess_rel_ratio_sample' : "max",
'bytes_dl_sample' : "max",
'bytes_ul_sample' : "max",
'x2_ho_avg': 'min',
'rsrp_sample': 'min',
'rsrq_sample':'min',
'serving_rsrp_sample': 'min',
'serving_rsrq_sample':'min',
'x2_ho_attempts_sample' : "max",
's1_ho_attempts_sample' : "max",
'ims_call_setup_time_sample' : "max",
'rtp_mos_dl_sample' : "max",
'rtp_mos_ul_sample' : "max",
'rtp_jitter_dl_sample' : "max",
'rtp_jitter_ul_sample' : "max"
}