[build-system]
requires = [
    'setuptools~=42.0',
    'wheel~=0.33.0',
    'numpy~=1.22.0',
    'pandas==1.4.2',
    'scikit-learn==1.1.0',
    'pystan==2.19.1.1',
    'prophet'
]
build-backend = "setuptools.build_meta"
