[build-system]
requires = [
    'setuptools~=42.0',
    'wheel~=0.33.0',
   'boto3==1.24.14',
    'joblib==1.1.0',
    'scikit-learn==1.1.0',
    'pandas~=1.4.2'
]
build-backend = "setuptools.build_meta"
