apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-rolebinding
  namespace: adtoolbox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-reader
subjects:
- namespace: adtoolbox
  kind: ServiceAccount
  name: default