apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: mycluster
  namespace: dask-operator
spec:
  worker:
    replicas: 2
    spec:
      containers:
        - name: worker
          image: "armdocker.rnd.ericsson.se/sandbox/daskautoscaler:v1.0"
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          args:
            - dask-worker
            - --name
            - $(DASK_WORKER_NAME)
          env:
            - name: WORKER_ENV
              value: hello-world # We dont test the value, just the name
  scheduler:
    spec:
      containers:
        - name: scheduler
          image: "armdocker.rnd.ericsson.se/sandbox/daskautoscaler:v1.0"
          imagePullPolicy: "Always"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          args:
            - dask-scheduler
          ports:
            - name: tcp-comm
              containerPort: 8786
              protocol: TCP
            - name: http-dashboard
              containerPort: 8787
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http-dashboard
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: http-dashboard
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 20

    service:
      type: NodePort
      selector:
        dask.org/cluster-name: mycluster
        dask.org/component: scheduler
      ports:
        - name: tcp-comm
          protocol: TCP
          port: 8786
          targetPort: "tcp-comm"
        - name: http-dashboard
          protocol: TCP
          port: 8787
          targetPort: "http-dashboard"