[build-system]
requires = [
    'setuptools~=42.0',
    'wheel~=0.33.0',
    'numpy~=1.6',
    'fastapi==0.78.0',
    'uvicorn==0.17.6',
    'pydantic==1.9.1'

]
build-backend = "setuptools.build_meta"
